# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getmtime_ms": "00_core.ipynb",
         "get_change_file": "00_core.ipynb",
         "MiscMagics": "04_misc.ipynb",
         "AssetMagics": "01_viz.ipynb",
         "SnippetsMagics": "02_snip.ipynb",
         "VControlMagics": "03_ver.ipynb"}

modules = ["core.py",
           "viz.py",
           "snip.py",
           "ver.py",
           "misc.py"]

doc_url = "https://suredream.github.io/sniptool/"

git_url = "https://github.com/suredream/sniptool/tree/master/"

def custom_doc_links(name): return None
