# AUTOGENERATED! DO NOT EDIT! File to edit: 03_ver.ipynb (unless otherwise specified).

__all__ = []

# Cell
from nbdev.imports import *

# Internal Cell
from IPython.core.magic import Magics, magics_class, line_magic, cell_magic
import os

@magics_class
class VControlMagics(Magics):
    @line_magic
    def g(self, parameter_s: str):
        opts, argsl = self.parse_options(parameter_s, "drz", mode="string")
        args = argsl.split()
        if not args:
            os.system("git status")
        else:
            cmd, opts = args[0], " ".join(args[1:])
            assert os.path.isfile("ghconfig")
            cred = yaml.load(open("ghconfig"), Loader=yaml.BaseLoader)
            url = f'{cred["token"]}@{cred["repo"].replace("https://","")}'
            if cmd == "get":
                pass
            elif cmd == "push":
                os.system(f"git push {url} {opts}")
            elif cmd == "pull":
                os.system(f"git pull {url} {opts}")
            elif cmd == "loc":
                print(cred["repo"])
            elif cmd == "save":
                if not opts:
                    opts = "update"
                os.system(f'git add -u && git commit -m "{opts}"')
            else:
                os.system(f"git {cmd} {opts}")